name: buro_employee
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.26+54

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  #cupertino_icons: ^1.0.2
  syncfusion_flutter_pdf: ^29.1.38
  path_provider: ^2.1.1
  open_filex: ^4.4.0
  number_to_words: ^1.0.0
  url_launcher: ^6.3.1
  file_picker: ^10.1.9
  permission_handler: ^11.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
 

  shared_preferences: ^2.2.2
  datetime_picker_formfield: # this package will be discontinued, need to change alter solution
  flutter_localizations:
      sdk: flutter
  #flutter_cupertino_localizations:
  google_fonts: ^6.2.1
  otp_text_field: ^1.1.3
  equatable: ^2.0.5
  flutter_bloc: ^9.1.1

  dio: ^4.0.6

  dio_logging_interceptor: 1.0.1
  #dio: ^4.0.6 /// for logging interceptor use this dio version
  build_runner: ^2.3.3
  date_time_format: ^2.0.1
  sqflite: ^2.2.8+4
  path: ^1.8.2
  flutter_launcher_icons:
  flutter_svg: ^2.0.5



  #firebase plugins
  firebase_core:
  firebase_crashlytics:
  firebase_analytics:
  firebase_core_platform_interface:
  firebase_messaging:
  #firebase_remote_config: ^4.3.3


  #fluttertoast: ^8.1.2
  flutter_custom_clippers: ^2.0.0
  autocomplete_textfield: ^2.0.1
  modal_bottom_sheet: ^3.0.0

  csc_picker: ^0.2.6
  #dropdown_search: 5.0.6




flutter_launcher_icons:
  ios: true
  android: true
  image_path_ios: "assets/apple_icon.png"
  image_path_android: "assets/buro_launcher_icon_android.png"
  remove_alpha_ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.


flutter:
  assets:
    - assets/svgs/leave_apply_icon.svg
    - assets/svgs/leave_request.svg
    - assets/svgs/leave_authorization.svg
    - assets/svgs/field_visit.svg
    - assets/svgs/leave.svg
    - assets/svgs/buro_logo.svg
    - assets/svgs/report.svg
    - assets/svgs/buro_icon_white.svg
    - assets/buro_launcher_icon.png
    - assets/svgs/field_visit_icon.svg
    - assets/svgs/approval_request_icon.svg
    - assets/svgs/bill_submit_icon.svg
    - assets/svgs/my_request_icon.svg
    - assets/svgs/apply_leave_icon.svg
    - assets/svgs/calender_icon.svg
    - assets/svgs/collection_summery_icon.svg
    - assets/svgs/field_visit_module_icon.svg
    - assets/svgs/appraisal_icon.svg
    - assets/svgs/filter_icon.svg
    - assets/svgs/profile_image.png
    - assets/svgs/approve.svg
    - assets/svgs/download.svg
    - assets/svgs/pending_list.svg
    - assets/svgs/apply.svg
    - assets/buro_launcher_icon_android.png
    - assets/buro_launcher_icon_ios.png
    - assets/apple_icon.png





  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
       #   - images/a_dot_burr.jpeg
       #   - images/a_dot_ham.jpeg
  #   - images/a_dot_ham.jpeg

  # To add assets to your application, add an assets section, like this:


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
